<a href="https://colab.research.google.com/github/figaz123/scrappingdata/blob/main/Scrappingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os
import shutil
import glob

In [ ]:
os.getcwd()

'/content/drive/MyDrive/scrapping data/gabungan'

In [ ]:
os.chdir('/content/drive/MyDrive/scrapping data')

In [ ]:
os.getcwd()

'/content/drive/MyDrive/scrapping data'

In [ ]:
os.listdir()

['jakarta2.csv',
 'jakarta3.csv',
 'bandung1.csv',
 'bandung2.csv',
 'bandung3.csv',
 'sby1.csv',
 'sby2.csv',
 'sby3.csv',
 'medan1.csv',
 'medan2.csv',
 'medan3.csv',
 'bali1.csv',
 'bali2.csv',
 'bali3.csv',
 'lombok1.csv',
 'lombok2.csv',
 'lombok3.csv',
 'semarang1.csv',
 'semarang2.csv',
 'semarang3.csv',
 'jakarta1.csv',
 'bali4.csv',
 'bali5.csv',
 'bali6.csv',
 'bali7.csv',
 'bali8.csv',
 'bali9.csv',
 'jakarta4.csv',
 'jakarta5.csv',
 'jakarta6.csv',
 'jakarta7.csv',
 'jakarta8.csv',
 'jakarta9.csv',
 'sby4.csv',
 'sby5.csv',
 'sby6.csv',
 'sby7.csv',
 'sby8.csv',
 'sby9.csv',
 'lombok4.csv',
 'lombok5.csv',
 'lombok6.csv',
 'lombok7.csv',
 'lombok8.csv',
 'lombok9.csv',
 'medan4.csv',
 'medan5.csv',
 'medan6.csv',
 'medan7.csv',
 'medan8.csv',
 'medan9.csv',
 'semarang4.csv',
 'semarang5.csv',
 'semarang6.csv',
 'semarang7.csv',
 'semarang8.csv',
 'semarang9.csv',
 'bandung4.csv',
 'bandung5.csv',
 'bandung6.csv',
 'bandung7.csv',
 'bandung8.csv',
 'bandung9.csv',
 '.ipynb_checkpoints',
 'gabungan']

In [ ]:
test = 'jakarta1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 6,W4Efsd 7,W4Efsd 8,W4Efsd 9,FQ2IWe src,Jn12ke src,ah5Ghc,ah5Ghc 2,ah5Ghc 3,W6VQef
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Ragunan+Zoo/...,Ragunan Zoo,4.5,"(92,625)",·,Tourist attraction,Jl. Harsono RM No.1,Large zoo in a rainforest setting,·,Closed,⋅ Opens 7AM,https://lh5.googleusercontent.com/p/AF1QipMFYO...,https://lh3.googleusercontent.com/a/default-us...,"""Cuma karena dikarenakan ingin ke",wisata,"lain di jakarta jadi ...""",·
3,https://www.google.com/maps/place/Taman+Mini+I...,Taman Mini Indonesia Indah,4.6,"(141,446)",·,Tourist attraction,Park filled with sights about Indonesia,NaN,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOLCN...,https://lh3.googleusercontent.com/a/default-us...,"""Dimana lagi ada objek",wisata,"dan edukasi seperti ini, mohon Dinas ...""",·
4,https://www.google.com/maps/place/Taman+Suropa...,Taman Suropati,4.6,"(18,364)",·,Tourist attraction,"Jl. Taman Suropati No.5, RT.5/RW.5",City green space with trails & statues,·,Open now,NaN,https://lh5.googleusercontent.com/p/AF1QipPiAU...,https://lh3.googleusercontent.com/a/default-us...,"""A lot of art activities going on during weeke...",NaN,NaN,·

In [ ]:
test = 'bandung1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 6,W4Efsd 7,W4Efsd 8,W4Efsd 9,FQ2IWe src,Jn12ke src,ah5Ghc,ah5Ghc 2,ah5Ghc 3,W6VQef
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Dago+Dreampa...,Dago Dreampark,4.2,"(17,009)",·,Tourist attraction,Jl. Dago Giri Km. 2.2 Mekarwangi,Forest amusement park with photo ops,·,Closed,⋅ Opens 8AM,https://lh5.googleusercontent.com/p/AF1QipN49a...,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Taman+Hutan+...,Taman Hutan Raya Ir. H. Djuanda,4.5,"(14,193)",·,Tourist attraction,"Kompleks Tahura, Jl. Ir. H. Juanda No.99",Large nature preserve & botanical garden,·,Closed,⋅ Opens 8AM,https://lh5.googleusercontent.com/p/AF1QipPLZu...,https://lh3.googleusercontent.com/a/default-us...,"""Sekarang di desember 2021, ada objek",wisata,"baru di THR yaitu ...""",·
3,https://www.google.com/maps/place/Tebing+Kerat...,Tebing Keraton,4.5,"(8,594)",·,Tourist attraction,Destination for scenic views & sunsets,NaN,NaN,NaN,NaN,https://lh5.googleusercontent.com/proxy/So3Gxd...,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/The+Great+As...,The Great Asia Africa,4.5,"(13,675)",·,Tourist attraction,Jl. Raya Lembang - Bandung No.71,Park dedicated to several countries,·,Closed,⋅ Opens 9AM,https://lh5.googleusercontent.com/p/AF1QipM6jt...,NaN,NaN,NaN,NaN,NaN

In [ ]:
test = 'lombok1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,FQ2IWe src,Jn12ke src,ah5Ghc,W6VQef,W4Efsd 7,W4Efsd 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),·,Tujuan Wisata,Jl. Kuta Lombok,·,Buka 24 jam,https://lh5.googleusercontent.com/p/AF1QipOy9k...,https://lh3.googleusercontent.com/a/default-us...,"""Potensi wisata yang bagus""",·,NaN,NaN
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),·,Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMA_5...,https://lh3.googleusercontent.com/a/default-us...,"""wisata yg sangat ramah""",·,⋅ Buka Sel pukul 07.00,NaN
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),·,Tujuan Wisata,Desa,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMBiC...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata alam yang istimewa""",·,⋅ Buka Sel pukul 07.00,Air terjun cantik di tengah hutan
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),·,Tujuan Wisata,Desa tradisional dengan tur & pedagang,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipNpky...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata budaya bagus disini.""",·,⋅ Buka Sel pukul 08.00,NaN

In [ ]:
test = 'medan1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,W4Efsd 7,W4Efsd 8,W4Efsd 9,FQ2IWe src,Jn12ke src,ah5Ghc,ah5Ghc 2,ah5Ghc 3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/TAMAN+WISATA...,TAMAN WISATA DANAU SIOMBAK MARELAN,"3,9",(1.070),·,Tujuan Wisata,Jl. Ps. Nippon No.Ujung,·,Danau buatan & area rekreasi,·,Buka,⋅ Tutup pukul 20.00,https://lh5.googleusercontent.com/p/AF1QipNZpH...,https://lh3.googleusercontent.com/a/default-us...,"""Taman edukasi dan wisata keluarga yang nyaman...",NaN,NaN
2,https://www.google.com/maps/place/Istana+Maimu...,"Istana Maimun, Kota Medan.","4,4",(17.337),·,Tujuan Wisata,Jl. Brigjend Katamso No.66,·,Istana bersejarah plus pameran & toko,·,Tutup,⋅ Buka Sel pukul 08.00,https://lh5.googleusercontent.com/p/AF1QipO6CW...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata sejarah terbaik yang ada di Medan.""",NaN,NaN
3,https://www.google.com/maps/place/Taman+Sri+De...,Taman Sri Deli,"4,5",(1.480),·,Tujuan Wisata,"HMGP+HJQ, Jl. Sisingamangaraja",·,Tempat hangout bersejarah dgn air mancur,·,Buka,⋅ Tutup pukul 21.00,https://lh5.googleusercontent.com/p/AF1QipO-GB...,https://lh3.googleusercontent.com/a/default-us...,"""... di jadikan objek wisata kota Medan yg san...",NaN,NaN
4,https://www.google.com/maps/place/Upside+Down+...,Upside Down World Medan,"4,3",(496),·,Tujuan Wisata,Jl. K.H. Wahid Hasyim No.29,·,NaN,NaN,Buka,⋅ Tutup pukul 20.00,https://lh5.googleusercontent.com/p/AF1QipNkv3...,https://lh3.googleusercontent.com/a/default-us...,"""Alternatif yg menarik sebagai wisata kota Med...",NaN,NaN

In [ ]:
test = 'semarang1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,W4Efsd 7,W4Efsd 8,W4Efsd 9,FQ2IWe src,Jn12ke src,ah5Ghc,W6VQef
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Lawang+Sewu/...,Lawang Sewu,"4,6",(61.396),·,Tujuan Wisata,Jl. Pemuda,·,Bangunan bersejarah plus tur berpemandu,·,Buka,⋅ Tutup pukul 21.00,https://lh5.googleusercontent.com/p/AF1QipOBJu...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata sejarah yg berada di pusat kota.""",·
2,https://www.google.com/maps/place/Kota+Lama+Se...,Kota Lama Semarang,"4,7",(1.607),·,Tujuan Wisata,NaN,NaN,NaN,NaN,Buka 24 jam,NaN,https://lh5.googleusercontent.com/p/AF1QipNUVl...,https://lh3.googleusercontent.com/a/default-us...,"""Tempat wisata dan swa foto berlatar belakang ...",·
3,https://www.google.com/maps/place/Puri+Maeroko...,Puri Maerokoco,"4,4",(3.881),·,Tujuan Wisata,Jl. Puri Anjasmoro,·,Taman luas dengan rumah & perahu klasik,·,Tutup,⋅ Buka Sel pukul 07.00,https://lh5.googleusercontent.com/p/AF1QipNS9X...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata edukasi untuk mengenal budaya jawa ten...",·
4,https://www.google.com/maps/place/Brown+Canyon...,Brown Canyon,"4,2",(3.246),·,Tujuan Wisata,Lokasi tambang pasir dengan formasi unik,·,NaN,NaN,Buka 24 jam,NaN,https://lh5.googleusercontent.com/p/AF1QipPAjR...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata bekas penggalian tanah wadas.. lumayan...",·

In [ ]:
test = 'bali1.csv'
test = pd.read_csv(test)
test.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,W4Efsd 7,W4Efsd 8,W4Efsd 9,FQ2IWe src,Jn12ke src,ah5Ghc
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),·,Tujuan Wisata,Jl. Ir. Sutami,·,Air terjun kecil dengan kolam rendam,·,Tutup,⋅ Buka Sel pukul 06.30,https://lh5.googleusercontent.com/p/AF1QipNDJJ...,https://lh3.googleusercontent.com/a/default-us...,"""Objek wisata keren di sukawati"""
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),·,Tujuan Wisata,Jl. Monkey Forest,·,Kompleks pura dengan banyak monyet,·,Tutup,⋅ Buka Sel pukul 09.00,https://lh5.googleusercontent.com/p/AF1QipPaxN...,https://lh3.googleusercontent.com/a/default-us...,"""Tempat wisata sangat recomended di Ubud 👍"""
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),·,Tujuan Wisata,Jl. Kartika Plaza,·,Taman air dengan wahana & restoran,·,Tutup,⋅ Buka Sel pukul 10.00,https://lh5.googleusercontent.com/p/AF1QipMZ_p...,https://lh3.googleusercontent.com/a/default-us...,"""Tempat yg terbaik di Bali untuk wisata air"""
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),·,Tujuan Wisata,Cagar alam untuk spesies burung langka,NaN,NaN,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN2fr...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata alam di Bali bagian barat yang mempesona"""

In [ ]:
directory = 'gabungan'
parent_dir = '/content/drive/MyDrive/scrapping data'
path = os.path.join(parent_dir, directory)
os.mkdir(path)
print("Direktori '%s'" % directory)

FileExistsError: ignored

In [ ]:
gab_address = '/content/drive/MyDrive/scrapping data/gabungan'

In [ ]:
os.listdir()

['jakarta2.csv',
 'jakarta3.csv',
 'bandung1.csv',
 'bandung2.csv',
 'bandung3.csv',
 'sby1.csv',
 'sby2.csv',
 'sby3.csv',
 'medan1.csv',
 'medan2.csv',
 'medan3.csv',
 'bali1.csv',
 'bali2.csv',
 'bali3.csv',
 'lombok1.csv',
 'lombok2.csv',
 'lombok3.csv',
 'semarang1.csv',
 'semarang2.csv',
 'semarang3.csv',
 'jakarta1.csv',
 'bali4.csv',
 'bali5.csv',
 'bali6.csv',
 'bali7.csv',
 'bali8.csv',
 'bali9.csv',
 'jakarta4.csv',
 'jakarta5.csv',
 'jakarta6.csv',
 'jakarta7.csv',
 'jakarta8.csv',
 'jakarta9.csv',
 'sby4.csv',
 'sby5.csv',
 'sby6.csv',
 'sby7.csv',
 'sby8.csv',
 'sby9.csv',
 'lombok4.csv',
 'lombok5.csv',
 'lombok6.csv',
 'lombok7.csv',
 'lombok8.csv',
 'lombok9.csv',
 'medan4.csv',
 'medan5.csv',
 'medan6.csv',
 'medan7.csv',
 'medan8.csv',
 'medan9.csv',
 'semarang4.csv',
 'semarang5.csv',
 'semarang6.csv',
 'semarang7.csv',
 'semarang8.csv',
 'semarang9.csv',
 'bandung4.csv',
 'bandung5.csv',
 'bandung6.csv',
 'bandung7.csv',
 'bandung8.csv',
 'bandung9.csv',
 '.ipynb_checkpoints',
 'gabungan']

In [ ]:
files = glob.iglob(os.path.join(parent_dir, '*.csv'))

In [ ]:
for file in files:
  if os.path.isfile(file):
    shutil.copy(file, gab_address)

In [ ]:
os.listdir(gab_address)

['gabungan_final',
 'jakarta2.csv',
 'sby3.csv',
 'bandung2.csv',
 'bandung3.csv',
 'medan3.csv',
 'bandung1.csv',
 'medan1.csv',
 'medan2.csv',
 'jakarta3.csv',
 'sby2.csv',
 'sby1.csv',
 'bali1.csv',
 'bali3.csv',
 'bali2.csv',
 'lombok1.csv',
 'semarang3.csv',
 'lombok2.csv',
 'semarang1.csv',
 'lombok3.csv',
 'jakarta1.csv',
 'semarang2.csv',
 'bali4.csv',
 'bali5.csv',
 'bali6.csv',
 'bali9.csv',
 'bali8.csv',
 'bali7.csv',
 'jakarta4.csv',
 'jakarta5.csv',
 'jakarta6.csv',
 'jakarta7.csv',
 'jakarta8.csv',
 'jakarta9.csv',
 'sby4.csv',
 'sby6.csv',
 'sby7.csv',
 'sby5.csv',
 'sby8.csv',
 'sby9.csv',
 'lombok4.csv',
 'lombok5.csv',
 'lombok6.csv',
 'lombok7.csv',
 'lombok8.csv',
 'lombok9.csv',
 'medan4.csv',
 'medan5.csv',
 'medan6.csv',
 'medan8.csv',
 'medan7.csv',
 'medan9.csv',
 'semarang4.csv',
 'semarang6.csv',
 'semarang5.csv',
 'semarang8.csv',
 'semarang7.csv',
 'semarang9.csv',
 'bandung4.csv',
 'bandung6.csv',
 'bandung5.csv',
 'bandung7.csv',
 'bandung8.csv',
 'bandung9.csv',
 'combined_csv.csv',
 '.ipynb_checkpoints',
 'jakarta.csv',
 'sby.csv',
 'medan.csv',
 'bandung.csv',
 'bali.csv',
 'semarang.csv']

In [ ]:
os.chdir(gab_address)
os.getcwd()

'/content/drive/MyDrive/scrapping data/gabungan'

In [ ]:
os.listdir()

['gabungan_final',
 'jakarta2.csv',
 'sby3.csv',
 'bandung2.csv',
 'bandung3.csv',
 'medan3.csv',
 'bandung1.csv',
 'medan1.csv',
 'medan2.csv',
 'jakarta3.csv',
 'sby2.csv',
 'sby1.csv',
 'bali1.csv',
 'bali3.csv',
 'bali2.csv',
 'lombok1.csv',
 'semarang3.csv',
 'lombok2.csv',
 'semarang1.csv',
 'lombok3.csv',
 'jakarta1.csv',
 'semarang2.csv',
 'bali4.csv',
 'bali5.csv',
 'bali6.csv',
 'bali9.csv',
 'bali8.csv',
 'bali7.csv',
 'jakarta4.csv',
 'jakarta5.csv',
 'jakarta6.csv',
 'jakarta7.csv',
 'jakarta8.csv',
 'jakarta9.csv',
 'sby4.csv',
 'sby6.csv',
 'sby7.csv',
 'sby5.csv',
 'sby8.csv',
 'sby9.csv',
 'lombok4.csv',
 'lombok5.csv',
 'lombok6.csv',
 'lombok7.csv',
 'lombok8.csv',
 'lombok9.csv',
 'medan4.csv',
 'medan5.csv',
 'medan6.csv',
 'medan8.csv',
 'medan7.csv',
 'medan9.csv',
 'semarang4.csv',
 'semarang6.csv',
 'semarang5.csv',
 'semarang8.csv',
 'semarang7.csv',
 'semarang9.csv',
 'bandung4.csv',
 'bandung6.csv',
 'bandung5.csv',
 'bandung7.csv',
 'bandung8.csv',
 'bandung9.csv',
 'combined_csv.csv',
 '.ipynb_checkpoints',
 'jakarta.csv',
 'sby.csv',
 'medan.csv',
 'bandung.csv',
 'bali.csv',
 'semarang.csv']

In [ ]:
directory = 'gabungan_final'
path = os.path.join(gab_address, directory)
os.mkdir(path)
print("Direktori '%s'" % directory)

FileExistsError: ignored

In [ ]:
os.chdir(gab_address)
os.getcwd()

'/content/drive/MyDrive/scrapping data/gabungan'

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('jakarta*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("jakarta.csv", index=False)

In [ ]:
jakarta = 'jakarta.csv'
jakarta = pd.read_csv(jakarta)
jakarta.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 6,W4Efsd 7,W4Efsd 8,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",·,Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,·,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",·,Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,·,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",·,Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,·,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
jakarta.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
jakarta.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,description,Status_1,Status_2,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",·,Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,·,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",·,Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,·,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",·,Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,·,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
jakarta = jakarta.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','ah5Ghc 3','W6VQef', 'ah5Ghc 2','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
jakarta.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
jakarta.fillna('None', inplace=True)
jakarta.drop(jakarta.index[0:2], inplace=True)
jakarta.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,None,None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,None,None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Wisata+Sunga...,Wisata Sungai Kota Tua,4.5,"(1,281)",Tourist attraction,"Kota Tua, Jl. Kali Besar Tim. No.21, RT.7/RW.2",None,None,None,None,None,None,None,None,None,None,None,None
6,https://www.google.com/maps/place/Museum+Bank+...,Museum Bank Indonesia,4.7,"(9,536)",Tourist attraction,"Jl. Pintu Besar Utara No.3, RW.6",Old town area with colonial architecture,"""",None,None,None,None,None,None,None,None,None,None

In [ ]:
jakarta["Kota"]="Jakarta"
jakarta.to_csv("jakarta.csv", index=True)
os.listdir()
jakarta.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",None,None,None,None,None,None,None,None,None,Jakarta
3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,None,None,None,None,None,None,None,None,None,None,Jakarta
4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,None,None,None,None,None,None,None,None,None,None,Jakarta
5,https://www.google.com/maps/place/Wisata+Sunga...,Wisata Sungai Kota Tua,4.5,"(1,281)",Tourist attraction,"Kota Tua, Jl. Kali Besar Tim. No.21, RT.7/RW.2",None,None,None,None,None,None,None,None,None,None,None,Jakarta
6,https://www.google.com/maps/place/Museum+Bank+...,Museum Bank Indonesia,4.7,"(9,536)",Tourist attraction,"Jl. Pintu Besar Utara No.3, RW.6",Old town area with colonial architecture,"""",None,None,None,None,None,None,None,None,None,Jakarta

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('sby*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("sby.csv", index=False)

In [ ]:
sby = "sby.csv"
sby = pd.read_csv(sby)
sby.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,W4Efsd 7,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Jalan+Gula+S...,Jalan Gula Spot Foto,4.5,(548),·,Tourist attraction,"QP6Q+9HP, Jalan Gula",·,Photo spot amid dilapidated buildings,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sanggar+Agun...,Sanggar Agung Temple,4.5,"(2,174)",·,Tourist attraction,Jl. Sukolilo No.100,·,Beachside shrine with dragon decorations,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Ria+Beach+Ke...,Ria Beach Kenjeran,4.2,"(3,772)",·,Tourist attraction,Jalan Sukolilo No.100,·,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Hutan+Kota+B...,Hutan Kota Balas Klumprik,4.3,(662),·,Tourist attraction,Jl. Balas Klumprik,·,"Garden with a pergola, a lake & flowers",·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sby.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
sby.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,W4Efsd 5,description,Status_1,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Jalan+Gula+S...,Jalan Gula Spot Foto,4.5,(548),·,Tourist attraction,"QP6Q+9HP, Jalan Gula",·,Photo spot amid dilapidated buildings,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sanggar+Agun...,Sanggar Agung Temple,4.5,"(2,174)",·,Tourist attraction,Jl. Sukolilo No.100,·,Beachside shrine with dragon decorations,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Ria+Beach+Ke...,Ria Beach Kenjeran,4.2,"(3,772)",·,Tourist attraction,Jalan Sukolilo No.100,·,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Hutan+Kota+B...,Hutan Kota Balas Klumprik,4.3,(662),·,Tourist attraction,Jl. Balas Klumprik,·,"Garden with a pergola, a lake & flowers",·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sby = sby.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','ah5Ghc 3','W6VQef', 'ah5Ghc 2','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
sby.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Jalan+Gula+S...,Jalan Gula Spot Foto,4.5,(548),Tourist attraction,"QP6Q+9HP, Jalan Gula",Photo spot amid dilapidated buildings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sanggar+Agun...,Sanggar Agung Temple,4.5,"(2,174)",Tourist attraction,Jl. Sukolilo No.100,Beachside shrine with dragon decorations,"""Hanya skrg bisa dimasuki berbagai pengunjung ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Ria+Beach+Ke...,Ria Beach Kenjeran,4.2,"(3,772)",Tourist attraction,Jalan Sukolilo No.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Hutan+Kota+B...,Hutan Kota Balas Klumprik,4.3,(662),Tourist attraction,Jl. Balas Klumprik,"Garden with a pergola, a lake & flowers",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sby.fillna('None', inplace=True)
sby.drop(sby.index[0:1], inplace=True)
sby.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Jalan+Gula+S...,Jalan Gula Spot Foto,4.5,(548),Tourist attraction,"QP6Q+9HP, Jalan Gula",Photo spot amid dilapidated buildings,None,None,None,None,None,None,None,None,None,None,None
2,https://www.google.com/maps/place/Sanggar+Agun...,Sanggar Agung Temple,4.5,"(2,174)",Tourist attraction,Jl. Sukolilo No.100,Beachside shrine with dragon decorations,"""Hanya skrg bisa dimasuki berbagai pengunjung ...",None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Ria+Beach+Ke...,Ria Beach Kenjeran,4.2,"(3,772)",Tourist attraction,Jalan Sukolilo No.100,None,None,None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Hutan+Kota+B...,Hutan Kota Balas Klumprik,4.3,(662),Tourist attraction,Jl. Balas Klumprik,"Garden with a pergola, a lake & flowers",None,None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Suro+and+Boy...,Suro and Boyo Statue,4.6,"(4,883)",Tourist attraction,Jl. Diponegoro No.1-B,Sculpture with a shark & crocodile,None,None,None,None,None,None,None,None,None,None,None

In [ ]:
sby["Kota"]="Surabaya"
sby.to_csv("sby.csv", index=True)
os.listdir()
sby.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Jalan+Gula+S...,Jalan Gula Spot Foto,4.5,(548),Tourist attraction,"QP6Q+9HP, Jalan Gula",Photo spot amid dilapidated buildings,None,None,None,None,None,None,None,None,None,None,Surabaya
2,https://www.google.com/maps/place/Sanggar+Agun...,Sanggar Agung Temple,4.5,"(2,174)",Tourist attraction,Jl. Sukolilo No.100,Beachside shrine with dragon decorations,"""Hanya skrg bisa dimasuki berbagai pengunjung ...",None,None,None,None,None,None,None,None,None,Surabaya
3,https://www.google.com/maps/place/Ria+Beach+Ke...,Ria Beach Kenjeran,4.2,"(3,772)",Tourist attraction,Jalan Sukolilo No.100,None,None,None,None,None,None,None,None,None,None,None,Surabaya
4,https://www.google.com/maps/place/Hutan+Kota+B...,Hutan Kota Balas Klumprik,4.3,(662),Tourist attraction,Jl. Balas Klumprik,"Garden with a pergola, a lake & flowers",None,None,None,None,None,None,None,None,None,None,Surabaya
5,https://www.google.com/maps/place/Suro+and+Boy...,Suro and Boyo Statue,4.6,"(4,883)",Tourist attraction,Jl. Diponegoro No.1-B,Sculpture with a shark & crocodile,None,None,None,None,None,None,None,None,None,None,Surabaya

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('medan*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("medan.csv", index=False)

In [ ]:
medan = "medan.csv"
medan = pd.read_csv(medan)
medan.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,FQ2IWe src,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Pemandian/da...,Pemandian,"4,1",(716),·,Tujuan Wisata,9M68+MGP,·,Sungai indah untuk mandi dan bersantai,https://lh5.googleusercontent.com/p/AF1QipP6dy...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Kampung+Outb...,Kampung Outbound Pancur Batu,"4,5",(144),·,Tujuan Wisata,Jl. Dusun,·,Istana bersejarah plus pameran & toko,https://lh5.googleusercontent.com/p/AF1QipOiKl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Taman+Lope+L...,Taman Lope Lope Bulu Cina,"4,0",(131),·,Tujuan Wisata,"PH5G+2H8, Jl. Sei Deli, Silalas, Medan Bar",·,Gereja Katolik bergaya Indo-Mogul,https://lh5.googleusercontent.com/p/AF1QipP5W4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Kampung+Wisa...,Kampung Wisata Ramah Anak Belawan Bahari,"4,9",(34),·,Tujuan Wisata,Lingkungan Xll Kelurahan,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipObyr...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
medan.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
medan.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,W4Efsd 5,description,FQ2IWe src,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Pemandian/da...,Pemandian,"4,1",(716),·,Tujuan Wisata,9M68+MGP,·,Sungai indah untuk mandi dan bersantai,https://lh5.googleusercontent.com/p/AF1QipP6dy...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Kampung+Outb...,Kampung Outbound Pancur Batu,"4,5",(144),·,Tujuan Wisata,Jl. Dusun,·,Istana bersejarah plus pameran & toko,https://lh5.googleusercontent.com/p/AF1QipOiKl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Taman+Lope+L...,Taman Lope Lope Bulu Cina,"4,0",(131),·,Tujuan Wisata,"PH5G+2H8, Jl. Sei Deli, Silalas, Medan Bar",·,Gereja Katolik bergaya Indo-Mogul,https://lh5.googleusercontent.com/p/AF1QipP5W4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Kampung+Wisa...,Kampung Wisata Ramah Anak Belawan Bahari,"4,9",(34),·,Tujuan Wisata,Lingkungan Xll Kelurahan,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipObyr...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
medan = medan.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','ah5Ghc 3','W6VQef', 'ah5Ghc 2','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
medan.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Pemandian/da...,Pemandian,"4,1",(716),Tujuan Wisata,9M68+MGP,Sungai indah untuk mandi dan bersantai,"""Tidak jauh dari",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Kampung+Outb...,Kampung Outbound Pancur Batu,"4,5",(144),Tujuan Wisata,Jl. Dusun,Istana bersejarah plus pameran & toko,"""Tempat yg sejuk.dan TDK jauh dari",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Taman+Lope+L...,Taman Lope Lope Bulu Cina,"4,0",(131),Tujuan Wisata,"PH5G+2H8, Jl. Sei Deli, Silalas, Medan Bar",Gereja Katolik bergaya Indo-Mogul,"""Ayo bantu wisata lokal ini.. ramai ramai data...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Kampung+Wisa...,Kampung Wisata Ramah Anak Belawan Bahari,"4,9",(34),Tujuan Wisata,Lingkungan Xll Kelurahan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
medan.fillna('None', inplace=True)
medan.drop(medan.index[0:1], inplace=True)
medan.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Pemandian/da...,Pemandian,"4,1",(716),Tujuan Wisata,9M68+MGP,Sungai indah untuk mandi dan bersantai,"""Tidak jauh dari",None,None,None,None,None,None,None,None,None,None
2,https://www.google.com/maps/place/Kampung+Outb...,Kampung Outbound Pancur Batu,"4,5",(144),Tujuan Wisata,Jl. Dusun,Istana bersejarah plus pameran & toko,"""Tempat yg sejuk.dan TDK jauh dari",None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Taman+Lope+L...,Taman Lope Lope Bulu Cina,"4,0",(131),Tujuan Wisata,"PH5G+2H8, Jl. Sei Deli, Silalas, Medan Bar",Gereja Katolik bergaya Indo-Mogul,"""Ayo bantu wisata lokal ini.. ramai ramai data...",None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Kampung+Wisa...,Kampung Wisata Ramah Anak Belawan Bahari,"4,9",(34),Tujuan Wisata,Lingkungan Xll Kelurahan,None,None,None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Central+Park...,Central Park Zoo & Resort,"4,5",(1.789),Taman bermain,"20, Jl. Jamin Ginting No.Km, RW.4","Kucing besar, taman air & wahana udara","""Menarik dan menjadi salah satu",None,None,None,None,None,None,None,None,None,None

In [ ]:
medan["Kota"]="Medan"
medan.to_csv("medan.csv", index=True)
os.listdir()
medan.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Pemandian/da...,Pemandian,"4,1",(716),Tujuan Wisata,9M68+MGP,Sungai indah untuk mandi dan bersantai,"""Tidak jauh dari",None,None,None,None,None,None,None,None,None,Medan
2,https://www.google.com/maps/place/Kampung+Outb...,Kampung Outbound Pancur Batu,"4,5",(144),Tujuan Wisata,Jl. Dusun,Istana bersejarah plus pameran & toko,"""Tempat yg sejuk.dan TDK jauh dari",None,None,None,None,None,None,None,None,None,Medan
3,https://www.google.com/maps/place/Taman+Lope+L...,Taman Lope Lope Bulu Cina,"4,0",(131),Tujuan Wisata,"PH5G+2H8, Jl. Sei Deli, Silalas, Medan Bar",Gereja Katolik bergaya Indo-Mogul,"""Ayo bantu wisata lokal ini.. ramai ramai data...",None,None,None,None,None,None,None,None,None,Medan
4,https://www.google.com/maps/place/Kampung+Wisa...,Kampung Wisata Ramah Anak Belawan Bahari,"4,9",(34),Tujuan Wisata,Lingkungan Xll Kelurahan,None,None,None,None,None,None,None,None,None,None,None,Medan
5,https://www.google.com/maps/place/Central+Park...,Central Park Zoo & Resort,"4,5",(1.789),Taman bermain,"20, Jl. Jamin Ginting No.Km, RW.4","Kucing besar, taman air & wahana udara","""Menarik dan menjadi salah satu",None,None,None,None,None,None,None,None,None,Medan

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('bandung*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("bandung.csv", index=False)

In [ ]:
bandung = "bandung.csv"
bandung = pd.read_csv(bandung)
bandung.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 6,W4Efsd 7,W4Efsd 8,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Museum+3D/da...,Museum 3D,4.6,(730),·,Tourist attraction,"4HXW+CF8, Jalan Doktor Setiabudi",Forest amusement park with photo ops,Closed,⋅ Opens 9AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sarae+Hills/...,Sarae Hills,4.5,(609),·,Tourist attraction,"Jl. Pagermaneuh, RT.05/RW./07",Large nature preserve & botanical garden,Closed,⋅ Opens 10AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Vanda+Park/d...,Vanda Park,4.4,"(2,929)",·,Tourist attraction,Jl. Merdeka No.9,Destination for scenic views & sunsets,Open 24 hours,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Plaza+Cikapu...,Plaza Cikapundung River Spot,4.3,"(4,614)",·,Tourist attraction,"3JH5+XG9, Jl. Dr. Ir. Sukarno",Cafe with photo ops & Bandung vistas,Open 24 hours,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bandung.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
bandung.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,description,Status_1,Status_2,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Museum+3D/da...,Museum 3D,4.6,(730),·,Tourist attraction,"4HXW+CF8, Jalan Doktor Setiabudi",Forest amusement park with photo ops,Closed,⋅ Opens 9AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sarae+Hills/...,Sarae Hills,4.5,(609),·,Tourist attraction,"Jl. Pagermaneuh, RT.05/RW./07",Large nature preserve & botanical garden,Closed,⋅ Opens 10AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Vanda+Park/d...,Vanda Park,4.4,"(2,929)",·,Tourist attraction,Jl. Merdeka No.9,Destination for scenic views & sunsets,Open 24 hours,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Plaza+Cikapu...,Plaza Cikapundung River Spot,4.3,"(4,614)",·,Tourist attraction,"3JH5+XG9, Jl. Dr. Ir. Sukarno",Cafe with photo ops & Bandung vistas,Open 24 hours,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bandung = bandung.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','ah5Ghc 3','W6VQef', 'ah5Ghc 2','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
bandung.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Museum+3D/da...,Museum 3D,4.6,(730),Tourist attraction,"4HXW+CF8, Jalan Doktor Setiabudi",Forest amusement park with photo ops,"""Rekomended banget untuk tujuan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Sarae+Hills/...,Sarae Hills,4.5,(609),Tourist attraction,"Jl. Pagermaneuh, RT.05/RW./07",Large nature preserve & botanical garden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Vanda+Park/d...,Vanda Park,4.4,"(2,929)",Tourist attraction,Jl. Merdeka No.9,Destination for scenic views & sunsets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Plaza+Cikapu...,Plaza Cikapundung River Spot,4.3,"(4,614)",Tourist attraction,"3JH5+XG9, Jl. Dr. Ir. Sukarno",Cafe with photo ops & Bandung vistas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bandung.fillna('None', inplace=True)
bandung.drop(bandung.index[0:1], inplace=True)
bandung.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Museum+3D/da...,Museum 3D,4.6,(730),Tourist attraction,"4HXW+CF8, Jalan Doktor Setiabudi",Forest amusement park with photo ops,"""Rekomended banget untuk tujuan",None,None,None,None,None,None,None,None,None,None
2,https://www.google.com/maps/place/Sarae+Hills/...,Sarae Hills,4.5,(609),Tourist attraction,"Jl. Pagermaneuh, RT.05/RW./07",Large nature preserve & botanical garden,None,None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Vanda+Park/d...,Vanda Park,4.4,"(2,929)",Tourist attraction,Jl. Merdeka No.9,Destination for scenic views & sunsets,None,None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Plaza+Cikapu...,Plaza Cikapundung River Spot,4.3,"(4,614)",Tourist attraction,"3JH5+XG9, Jl. Dr. Ir. Sukarno",Cafe with photo ops & Bandung vistas,None,None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Taman+Maluku...,Taman Maluku,4.5,"(1,081)",Tourist attraction,"Picnics, mature trees & colonial statue",None,None,None,None,None,None,None,None,None,None,None,None

In [ ]:
bandung["Kota"]="Bandung"
bandung.to_csv("bandung.csv", index=True)
os.listdir()
bandung.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Museum+3D/da...,Museum 3D,4.6,(730),Tourist attraction,"4HXW+CF8, Jalan Doktor Setiabudi",Forest amusement park with photo ops,"""Rekomended banget untuk tujuan",None,None,None,None,None,None,None,None,None,Bandung
2,https://www.google.com/maps/place/Sarae+Hills/...,Sarae Hills,4.5,(609),Tourist attraction,"Jl. Pagermaneuh, RT.05/RW./07",Large nature preserve & botanical garden,None,None,None,None,None,None,None,None,None,None,Bandung
3,https://www.google.com/maps/place/Vanda+Park/d...,Vanda Park,4.4,"(2,929)",Tourist attraction,Jl. Merdeka No.9,Destination for scenic views & sunsets,None,None,None,None,None,None,None,None,None,None,Bandung
4,https://www.google.com/maps/place/Plaza+Cikapu...,Plaza Cikapundung River Spot,4.3,"(4,614)",Tourist attraction,"3JH5+XG9, Jl. Dr. Ir. Sukarno",Cafe with photo ops & Bandung vistas,None,None,None,None,None,None,None,None,None,None,Bandung
5,https://www.google.com/maps/place/Taman+Maluku...,Taman Maluku,4.5,"(1,081)",Tourist attraction,"Picnics, mature trees & colonial statue",None,None,None,None,None,None,None,None,None,None,None,Bandung

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('bali*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("bali.csv", index=False)

In [ ]:
bali = "bali.csv"
bali = pd.read_csv(bali)
bali.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,W4Efsd 7,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),·,Tujuan Wisata,Jl. Ir. Sutami,·,Air terjun kecil dengan kolam rendam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),·,Tujuan Wisata,Jl. Monkey Forest,·,Kompleks pura dengan banyak monyet,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),·,Tujuan Wisata,Jl. Kartika Plaza,·,Taman air dengan wahana & restoran,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),·,Tujuan Wisata,Cagar alam untuk spesies burung langka,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bali.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
bali.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,W4Efsd 5,description,Status_1,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),·,Tujuan Wisata,Jl. Ir. Sutami,·,Air terjun kecil dengan kolam rendam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),·,Tujuan Wisata,Jl. Monkey Forest,·,Kompleks pura dengan banyak monyet,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),·,Tujuan Wisata,Jl. Kartika Plaza,·,Taman air dengan wahana & restoran,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),·,Tujuan Wisata,Cagar alam untuk spesies burung langka,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bali = bali.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','W6VQef', 'ah5Ghc 2','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
bali.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),Tujuan Wisata,Jl. Ir. Sutami,Air terjun kecil dengan kolam rendam,"""Objek wisata keren di sukawati""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),Tujuan Wisata,Jl. Monkey Forest,Kompleks pura dengan banyak monyet,"""Tempat wisata sangat recomended di Ubud 👍""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),Tujuan Wisata,Jl. Kartika Plaza,Taman air dengan wahana & restoran,"""Tempat yg terbaik di Bali untuk wisata air""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),Tujuan Wisata,Cagar alam untuk spesies burung langka,NaN,"""Wisata alam di Bali bagian barat yang mempesona""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bali.fillna('None', inplace=True)
bali.drop(bali.index[0:1], inplace=True)

bali.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),Tujuan Wisata,Jl. Ir. Sutami,Air terjun kecil dengan kolam rendam,"""Objek wisata keren di sukawati""",None,None,None,None,None,None,None,None,None,None
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),Tujuan Wisata,Jl. Monkey Forest,Kompleks pura dengan banyak monyet,"""Tempat wisata sangat recomended di Ubud 👍""",None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),Tujuan Wisata,Jl. Kartika Plaza,Taman air dengan wahana & restoran,"""Tempat yg terbaik di Bali untuk wisata air""",None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),Tujuan Wisata,Cagar alam untuk spesies burung langka,None,"""Wisata alam di Bali bagian barat yang mempesona""",None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Bukit+Campuh...,Bukit Campuhan,"4,5",(2.104),Tujuan Wisata,Jl. Bangkiang Sidem,Jalur pendakian di hutan rimbun,"""tempat wisata yg ramah lingkungan dan jauh da...",None,None,None,None,None,None,None,None,None,None

In [ ]:
bali["Kota"]="Bali"
bali.to_csv("bali.csv", index=True)
os.listdir()
bali.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Tegenungan+W...,Tegenungan Waterfall,"4,3",(21.592),Tujuan Wisata,Jl. Ir. Sutami,Air terjun kecil dengan kolam rendam,"""Objek wisata keren di sukawati""",None,None,None,None,None,None,None,None,None,Bali
2,https://www.google.com/maps/place/Mandala+Suci...,Mandala Suci Wenara Wana,"4,5",(34.238),Tujuan Wisata,Jl. Monkey Forest,Kompleks pura dengan banyak monyet,"""Tempat wisata sangat recomended di Ubud 👍""",None,None,None,None,None,None,None,None,None,Bali
3,https://www.google.com/maps/place/Waterbom+Bal...,Waterbom Bali,"4,7",(9.939),Tujuan Wisata,Jl. Kartika Plaza,Taman air dengan wahana & restoran,"""Tempat yg terbaik di Bali untuk wisata air""",None,None,None,None,None,None,None,None,None,Bali
4,https://www.google.com/maps/place/Taman+Nasion...,Taman Nasional Bali Barat,"4,5",(2.867),Tujuan Wisata,Cagar alam untuk spesies burung langka,None,"""Wisata alam di Bali bagian barat yang mempesona""",None,None,None,None,None,None,None,None,None,Bali
5,https://www.google.com/maps/place/Bukit+Campuh...,Bukit Campuhan,"4,5",(2.104),Tujuan Wisata,Jl. Bangkiang Sidem,Jalur pendakian di hutan rimbun,"""tempat wisata yg ramah lingkungan dan jauh da...",None,None,None,None,None,None,None,None,None,Bali

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('semarang*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("semarang.csv", index=False)

In [ ]:
semarang = "semarang.csv"
semarang = pd.read_csv(semarang)
semarang.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 6,W4Efsd 7,W4Efsd 8,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Diponegoro+P...,Diponegoro Park,"4,5",(865),·,Tujuan Wisata,"XCR8+WM3, Jl. Sultan Agung",Ruang hijau di bundaran lalu lintas,Buka 24 jam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Semarang+Con...,Semarang Contemporary Art Gallery,"4,6",(1.126),·,Tujuan Wisata,Jl. Taman Srigunting No.5-6,Galeri indah untuk seni kontemporer,Tutup,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Semirang,"4,4",(912),·,Tujuan Wisata,Loket wisata,Air terjun kecil indah & kolam renang,Tutup,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Anjungan+Kot...,Anjungan Kota Semarang,"4,5",(74),·,Tujuan Wisata,29QP+QCQ,Pantai terpencil & pemancingan populer,Tutup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
semarang.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
semarang.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,description,Status_1,Status_2,...,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Diponegoro+P...,Diponegoro Park,"4,5",(865),·,Tujuan Wisata,"XCR8+WM3, Jl. Sultan Agung",Ruang hijau di bundaran lalu lintas,Buka 24 jam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Semarang+Con...,Semarang Contemporary Art Gallery,"4,6",(1.126),·,Tujuan Wisata,Jl. Taman Srigunting No.5-6,Galeri indah untuk seni kontemporer,Tutup,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Semirang,"4,4",(912),·,Tujuan Wisata,Loket wisata,Air terjun kecil indah & kolam renang,Tutup,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Anjungan+Kot...,Anjungan Kota Semarang,"4,5",(74),·,Tujuan Wisata,29QP+QCQ,Pantai terpencil & pemancingan populer,Tutup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
semarang = semarang.drop(columns=['W4Efsd', 'W4Efsd 9','Status_1','Status_2','FQ2IWe src','Jn12ke src','W6VQef','W4Efsd 3', 'W4Efsd 5','fontBodyMedium'])
semarang.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Diponegoro+P...,Diponegoro Park,"4,5",(865),Tujuan Wisata,"XCR8+WM3, Jl. Sultan Agung",Ruang hijau di bundaran lalu lintas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Semarang+Con...,Semarang Contemporary Art Gallery,"4,6",(1.126),Tujuan Wisata,Jl. Taman Srigunting No.5-6,Galeri indah untuk seni kontemporer,"""Tempat wisata recomended bagi yang suka foto ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Semirang,"4,4",(912),Tujuan Wisata,Loket wisata,Air terjun kecil indah & kolam renang,"""tempat wisata asik & murmer, recommended 👍""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.google.com/maps/place/Anjungan+Kot...,Anjungan Kota Semarang,"4,5",(74),Tujuan Wisata,29QP+QCQ,Pantai terpencil & pemancingan populer,"""Tempat pertemuan sekaligus wisata di taman pu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
semarang.fillna('None', inplace=True)
semarang.drop(semarang.index[0:1], inplace=True)
semarang.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Diponegoro+P...,Diponegoro Park,"4,5",(865),Tujuan Wisata,"XCR8+WM3, Jl. Sultan Agung",Ruang hijau di bundaran lalu lintas,None,None,None,None,None,None,None,None,None,None,None
2,https://www.google.com/maps/place/Semarang+Con...,Semarang Contemporary Art Gallery,"4,6",(1.126),Tujuan Wisata,Jl. Taman Srigunting No.5-6,Galeri indah untuk seni kontemporer,"""Tempat wisata recomended bagi yang suka foto ...",None,None,None,None,None,None,None,None,None,None
3,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Semirang,"4,4",(912),Tujuan Wisata,Loket wisata,Air terjun kecil indah & kolam renang,"""tempat wisata asik & murmer, recommended 👍""",None,None,None,None,None,None,None,None,None,None
4,https://www.google.com/maps/place/Anjungan+Kot...,Anjungan Kota Semarang,"4,5",(74),Tujuan Wisata,29QP+QCQ,Pantai terpencil & pemancingan populer,"""Tempat pertemuan sekaligus wisata di taman pu...",None,None,None,None,None,None,None,None,None,None
5,https://www.google.com/maps/place/Taman+Budaya...,Taman Budaya Raden Saleh,"4,4",(3.101),Tujuan Wisata,Jl. Sriwijaya No.29,Wihara Buddha dengan pagoda dan taman,"""Temapt wisata edukasi yg tepat""",None,None,None,None,None,None,None,None,None,None

In [ ]:
semarang["Kota"]="Semarang"
semarang.to_csv("semarang.csv", index=True)
semarang

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Diponegoro+P...,Diponegoro Park,"4,5",(865),Tujuan Wisata,"XCR8+WM3, Jl. Sultan Agung",Ruang hijau di bundaran lalu lintas,None,None,None,None,None,None,None,None,None,None,Semarang
2,https://www.google.com/maps/place/Semarang+Con...,Semarang Contemporary Art Gallery,"4,6",(1.126),Tujuan Wisata,Jl. Taman Srigunting No.5-6,Galeri indah untuk seni kontemporer,"""Tempat wisata recomended bagi yang suka foto ...",None,None,None,None,None,None,None,None,None,Semarang
3,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Semirang,"4,4",(912),Tujuan Wisata,Loket wisata,Air terjun kecil indah & kolam renang,"""tempat wisata asik & murmer, recommended 👍""",None,None,None,None,None,None,None,None,None,Semarang
4,https://www.google.com/maps/place/Anjungan+Kot...,Anjungan Kota Semarang,"4,5",(74),Tujuan Wisata,29QP+QCQ,Pantai terpencil & pemancingan populer,"""Tempat pertemuan sekaligus wisata di taman pu...",None,None,None,None,None,None,None,None,None,Semarang
5,https://www.google.com/maps/place/Taman+Budaya...,Taman Budaya Raden Saleh,"4,4",(3.101),Tujuan Wisata,Jl. Sriwijaya No.29,Wihara Buddha dengan pagoda dan taman,"""Temapt wisata edukasi yg tepat""",None,None,None,None,None,None,None,None,None,Semarang
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4566,None,None,None,None,None,None,None,None,2281.0,https://www.google.com/maps/place/Pondok+Kopi+...,Pondok Kopi Umbul Sidomukti,"4,5",(14.909),Kafe,R948+M9X,None,"""",Semarang
4567,None,None,None,None,None,None,None,None,2282.0,https://www.google.com/maps/place/Aquatico+Aqu...,Aquatico Aquascape Semarang,"4,5",(319),Pusat Perbelanjaan,"Jl. Wonodri Baru Atas, RT.8 / Rw2 No.1",None,Belanja di toko,Semarang
4568,None,None,None,None,None,None,None,None,2283.0,https://www.google.com/maps/place/Semarang+Kot...,Semarang Kota,"5,0",(5),Taman Kota,2C5F+F2C,None,None,Semarang
4569,None,None,None,None,None,None,None,None,2284.0,https://www.google.com/maps/place/Masok/data=!...,Masok,None,None,Taman,Jl. Setia Budi No.12,None,None,Semarang
4570,None,None,None,None,None,None,None,None,2285.0,https://www.google.com/maps/place/Rekreasi/dat...,Rekreasi,None,None,Area Mendaki,WFVP+HM,None,None,Semarang

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('lombok*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("lombok.csv", index=False)

In [ ]:
lombok = "lombok.csv"
lombok = pd.read_csv(lombok)
lombok.head()

,hfpxzc href,qBF1Pd,MW4etd,UY7F9,W4Efsd,W4Efsd 2,W4Efsd 4,W4Efsd 5,W4Efsd 6,FQ2IWe src,Jn12ke src,ah5Ghc,W6VQef,W4Efsd 7,W4Efsd 8,W4Efsd 3,fontBodyMedium
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),·,Tujuan Wisata,Jl. Kuta Lombok,·,Buka 24 jam,https://lh5.googleusercontent.com/p/AF1QipOy9k...,https://lh3.googleusercontent.com/a/default-us...,"""Potensi wisata yang bagus""",·,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),·,Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMA_5...,https://lh3.googleusercontent.com/a/default-us...,"""wisata yg sangat ramah""",·,⋅ Buka Sel pukul 07.00,NaN,NaN,NaN
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),·,Tujuan Wisata,Desa,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMBiC...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata alam yang istimewa""",·,⋅ Buka Sel pukul 07.00,Air terjun cantik di tengah hutan,NaN,NaN
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),·,Tujuan Wisata,Desa tradisional dengan tur & pedagang,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipNpky...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata budaya bagus disini.""",·,⋅ Buka Sel pukul 08.00,NaN,NaN,NaN

In [ ]:
lombok.rename(columns = {'qBF1Pd' : 'Place', 'hfpxzc href': 'Source', 'MW4etd' : 'Rating', 'UY7F9' : 'Jumlah review', 'W4Efsd 2' : 'Type', 'W4Efsd 4': 'Address', 'W4Efsd 6' : 'description', 'W4Efsd 7': 'Status_1', 'W4Efsd 8': 'Status_2','ah5Ghc':'Komentar' }, inplace = True)
lombok.head()

,Source,Place,Rating,Jumlah review,W4Efsd,Type,Address,W4Efsd 5,description,FQ2IWe src,Jn12ke src,Komentar,W6VQef,Status_1,Status_2,W4Efsd 3,fontBodyMedium
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),·,Tujuan Wisata,Jl. Kuta Lombok,·,Buka 24 jam,https://lh5.googleusercontent.com/p/AF1QipOy9k...,https://lh3.googleusercontent.com/a/default-us...,"""Potensi wisata yang bagus""",·,NaN,NaN,NaN,NaN
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),·,Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMA_5...,https://lh3.googleusercontent.com/a/default-us...,"""wisata yg sangat ramah""",·,⋅ Buka Sel pukul 07.00,NaN,NaN,NaN
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),·,Tujuan Wisata,Desa,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipMBiC...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata alam yang istimewa""",·,⋅ Buka Sel pukul 07.00,Air terjun cantik di tengah hutan,NaN,NaN
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),·,Tujuan Wisata,Desa tradisional dengan tur & pedagang,·,Tutup,https://lh5.googleusercontent.com/p/AF1QipNpky...,https://lh3.googleusercontent.com/a/default-us...,"""Wisata budaya bagus disini.""",·,⋅ Buka Sel pukul 08.00,NaN,NaN,NaN

In [ ]:
lombok = lombok.drop(columns=['Status_1','Status_2','W4Efsd', 'W4Efsd 5','FQ2IWe src','Jn12ke src', 'W6VQef','W4Efsd 3','fontBodyMedium'])
lombok.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),Tujuan Wisata,Jl. Kuta Lombok,Buka 24 jam,"""Potensi wisata yang bagus"""
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",Tutup,"""wisata yg sangat ramah"""
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),Tujuan Wisata,Desa,Tutup,"""Wisata alam yang istimewa"""
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),Tujuan Wisata,Desa tradisional dengan tur & pedagang,Tutup,"""Wisata budaya bagus disini."""

In [ ]:
lombok.fillna('None', inplace=True)
lombok.drop(lombok.index[0:1], inplace=True)
lombok.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),Tujuan Wisata,Jl. Kuta Lombok,Buka 24 jam,"""Potensi wisata yang bagus"""
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",Tutup,"""wisata yg sangat ramah"""
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),Tujuan Wisata,Desa,Tutup,"""Wisata alam yang istimewa"""
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),Tujuan Wisata,Desa tradisional dengan tur & pedagang,Tutup,"""Wisata budaya bagus disini."""
5,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Sendang Gile,"4,6",(114),Tujuan Wisata,Air Terjun Sendang Gile,Tutup,"""Pilihan paling tepat buat yang suka wisata ai..."

In [ ]:
lombok["Kota"]="Lombok"
lombok.to_csv("lombok.csv", index=True)
lombok

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
1,https://www.google.com/maps/place/Bukit+Merese...,Bukit Merese Lombok (Kuta Lombok Hill),"4,7",(5.116),Tujuan Wisata,Jl. Kuta Lombok,Buka 24 jam,"""Potensi wisata yang bagus""",Lombok
2,https://www.google.com/maps/place/Wisata+di+Lo...,Wisata di Lombok,"4,5",(113),Tujuan Wisata,"Jogot Madani Residen, Jl. TGH. Lopan No.100",Tutup,"""wisata yg sangat ramah""",Lombok
3,https://www.google.com/maps/place/Air+Terjun+B...,Air Terjun Benang Kelambu,"4,5",(1.880),Tujuan Wisata,Desa,Tutup,"""Wisata alam yang istimewa""",Lombok
4,https://www.google.com/maps/place/Sade+Village...,Sade Village,"4,6",(6.400),Tujuan Wisata,Desa tradisional dengan tur & pedagang,Tutup,"""Wisata budaya bagus disini.""",Lombok
5,https://www.google.com/maps/place/Air+Terjun+S...,Air Terjun Sendang Gile,"4,6",(114),Tujuan Wisata,Air Terjun Sendang Gile,Tutup,"""Pilihan paling tepat buat yang suka wisata ai...",Lombok
...,...,...,...,...,...,...,...,...,...
1184,https://www.google.com/maps/place/Kabupaten+Lo...,Kabupaten Lombok Tengah,None,None,Nusa Tenggara Bar.,None,None,None,Lombok
1185,https://www.google.com/maps/place/Makam+Wali+N...,Makam Wali Nyato,"4,3",(51),Pemakaman,5876+J9M,None,"""",Lombok
1186,https://www.google.com/maps/place/Wisata+Alam+...,Wisata Alam Buah Naga,"4,4",(23),Rumah wisata,"Dusun Kebun Indah, Tanak Beak",None,"""Tempat wisata yang bagus untuk dikunjungi.""",Lombok
1187,https://www.google.com/maps/place/Happy+Wisata...,Happy Wisata Lombok,"4,9",(83),Biro Perjalanan dan Wisata,Jl. Gotong Royong,None,"""Wisata recomended di lombok""",Lombok
1188,https://www.google.com/maps/place/Lombok+Wonde...,Lombok Wonderland Tour and Travel,"5,0",(91),Penyelenggara Perjalanan,"Jl. Ade Irma Suryani, GPM Blok Gili Nanggu No:...",None,None,Lombok

In [ ]:
#check duplicate data
semarang.drop_duplicates(subset='Source', keep = False, inplace=True)
semarang.to_csv('semarang.csv', index=True)
semarang.head()

jakarta.drop_duplicates(subset='Source', keep = False, inplace=True)
jakarta.to_csv('jakarta.csv', index=True)
jakarta.head()

bali.drop_duplicates(subset='Source', keep = False, inplace=True)
bali.to_csv('bali.csv', index=True)
bali.head()

lombok.drop_duplicates(subset='Source', keep = False, inplace=True)
lombok.to_csv('lombok.csv', index=True)
lombok.head()

bandung.drop_duplicates(subset='Source', keep = False, inplace=True)
bandung.to_csv('bandung.csv', index=True)
bandung.head()

medan.drop_duplicates(subset='Source', keep = False, inplace=True)
medan.to_csv('medan.csv', index=True)
medan.head()

sby.drop_duplicates(subset='Source', keep = False, inplace=True)
sby.to_csv('sby.csv', index=True)
sby.head()

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
21,https://www.google.com/maps/place/Religious+To...,Religious Tourism MAmpel,4.7,(128),Tourist attraction,Jl. Ampel Masjid No.53,Photo spot amid dilapidated buildings,None,None,None,None,None,None,None,None,None,None,Surabaya
22,https://www.google.com/maps/place/Taman+Persah...,Taman Persahabatan,4.6,(995),Tourist attraction,Jl. Sulawesi No.67,Beachside shrine with dragon decorations,None,None,None,None,None,None,None,None,None,None,Surabaya
23,https://www.google.com/maps/place/Siola+Suraba...,Siola Surabaya Museum,4.6,"(6,535)",Tourist attraction,Tunjungan St No.1,Civic & domestic history exhibits,"""Birokrasi,",None,None,None,None,None,None,None,None,None,Surabaya
24,https://www.google.com/maps/place/Red+Bridge/d...,Red Bridge,4.5,"(2,252)",Tourist attraction,Kembang Jepun St No.192,Landmark bridge at a 1945 battle site,"""Selain bisa menjadi tempat",None,None,None,None,None,None,None,None,None,Surabaya
25,https://www.google.com/maps/place/Taman+Baruna...,Taman Barunawati,4.3,(500),Tourist attraction,Sculpture with a shark & crocodile,None,"""... menjadi salah satu destinasi",None,None,None,None,None,None,None,None,None,Surabaya

In [ ]:
#move the file to 'gabungan_final' directory
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/medan.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/medan.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/semarang.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/semarang.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/jakarta.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/jakarta.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/bandung.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/bandung.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/lombok.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/lombok.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/bali.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/bali.csv")
shutil.move("/content/drive/MyDrive/scrapping data/gabungan/sby.csv", "/content/drive/MyDrive/scrapping data/gabungan/gabungan_final/sby.csv")

In [ ]:
os.chdir('/content/drive/MyDrive/scrapping data/gabungan/gabungan_final')

In [ ]:
os.getcwd()

'/content/drive/MyDrive/scrapping data/gabungan/gabungan_final'

In [ ]:
os.listdir()

['jakarta.csv',
 'sby.csv',
 'medan.csv',
 'bandung.csv',
 'bali.csv',
 'semarang.csv',
 'lombok.csv']

In [ ]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("gabungan_semua.csv", index=False)

In [ ]:
gabungan = 'gabungan_semua.csv'
gabungan =pd.read_csv(gabungan)
gabungan.head()

,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Unnamed: 0.1,Source.1,Place.1,Rating.1,Jumlah review.1,Type.1,Address.1,description.1,Komentar.1,Kota
0,2,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",None,None,None,None,None,None,None,None,None,Jakarta
1,3,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,None,None,None,None,None,None,None,None,None,None,Jakarta
2,4,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,None,None,None,None,None,None,None,None,None,None,Jakarta
3,5,https://www.google.com/maps/place/Wisata+Sunga...,Wisata Sungai Kota Tua,4.5,"(1,281)",Tourist attraction,"Kota Tua, Jl. Kali Besar Tim. No.21, RT.7/RW.2",None,None,None,None,None,None,None,None,None,None,None,Jakarta
4,6,https://www.google.com/maps/place/Museum+Bank+...,Museum Bank Indonesia,4.7,"(9,536)",Tourist attraction,"Jl. Pintu Besar Utara No.3, RW.6",Old town area with colonial architecture,"""",None,None,None,None,None,None,None,None,None,Jakarta

In [ ]:
gabungan = gabungan.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'Source.1', 'Place.1', 'Rating.1', 'Jumlah review.1', 'Type.1', 'Address.1', 'description.1', 'Komentar.1'])
gabungan

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",Jakarta
1,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,None,Jakarta
2,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,None,Jakarta
3,https://www.google.com/maps/place/Wisata+Sunga...,Wisata Sungai Kota Tua,4.5,"(1,281)",Tourist attraction,"Kota Tua, Jl. Kali Besar Tim. No.21, RT.7/RW.2",None,None,Jakarta
4,https://www.google.com/maps/place/Museum+Bank+...,Museum Bank Indonesia,4.7,"(9,536)",Tourist attraction,"Jl. Pintu Besar Utara No.3, RW.6",Old town area with colonial architecture,"""",Jakarta
...,...,...,...,...,...,...,...,...,...
1089,https://www.google.com/maps/place/Air+Terjun+G...,Air Terjun Goa Batu Emas,"4,0",(51),Tujuan Wisata,C76F+78V,Tutup,None,Lombok
1090,https://www.google.com/maps/place/Alun+Alun+Ta...,Alun Alun Tastura,"4,3",(1.062),Tujuan Wisata,"77WC+5JM, Jl. Ahmad Yani",Buka,"""Sangat bagus untuk wisata keluarga ada kuline...",Lombok
1091,https://www.google.com/maps/place/Air+Terjun+G...,Air Terjun Gunung Janggot,"4,5",(30),Tujuan Wisata,"F963+RP7, Dusun seganteng",Buka 24 jam,"""Tempat wisata di daerah aik brik""",Lombok
1092,https://www.google.com/maps/place/Tereng+Kunin...,Tereng Kuning Aik Bone,"4,4",(31),Tujuan Wisata,"Tereng Kuning Aik Bone, Tereng Kuning Aik Bone",Buka 24 jam,None,Lombok
1093,https://www.google.com/maps/place/Objek+Wisata...,Objek Wisata Batu Bolong,"4,8",(13),Tujuan Wisata,F3R4+9Q7,Buka 24 jam,None,Lombok

In [ ]:
gabungan.to_csv("gabungan_semua.csv", index=True)
gabungan

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,https://www.google.com/maps/place/Jakarta+Hist...,Jakarta History Museum,4.6,"(20,176)",Tourist attraction,Jalan Taman Fatahillah No.1,Exhibits on the history of Jakarta,"""Kabarnya ada juga",Jakarta
1,https://www.google.com/maps/place/Faunaland+An...,Faunaland Ancol,4.5,"(3,044)",Tourist attraction,"VRGP+783, Ecovention Building - Ecopark, Jalan...",Zoo with shows & animal interaction,None,Jakarta
2,https://www.google.com/maps/place/Srengseng+Ci...,Srengseng City Forest,4.3,"(8,135)",Tourist attraction,"Jl. H. Kelik, RT.8/RW.6",Large green space with paved trails,None,Jakarta
3,https://www.google.com/maps/place/Wisata+Sunga...,Wisata Sungai Kota Tua,4.5,"(1,281)",Tourist attraction,"Kota Tua, Jl. Kali Besar Tim. No.21, RT.7/RW.2",None,None,Jakarta
4,https://www.google.com/maps/place/Museum+Bank+...,Museum Bank Indonesia,4.7,"(9,536)",Tourist attraction,"Jl. Pintu Besar Utara No.3, RW.6",Old town area with colonial architecture,"""",Jakarta
...,...,...,...,...,...,...,...,...,...
1089,https://www.google.com/maps/place/Air+Terjun+G...,Air Terjun Goa Batu Emas,"4,0",(51),Tujuan Wisata,C76F+78V,Tutup,None,Lombok
1090,https://www.google.com/maps/place/Alun+Alun+Ta...,Alun Alun Tastura,"4,3",(1.062),Tujuan Wisata,"77WC+5JM, Jl. Ahmad Yani",Buka,"""Sangat bagus untuk wisata keluarga ada kuline...",Lombok
1091,https://www.google.com/maps/place/Air+Terjun+G...,Air Terjun Gunung Janggot,"4,5",(30),Tujuan Wisata,"F963+RP7, Dusun seganteng",Buka 24 jam,"""Tempat wisata di daerah aik brik""",Lombok
1092,https://www.google.com/maps/place/Tereng+Kunin...,Tereng Kuning Aik Bone,"4,4",(31),Tujuan Wisata,"Tereng Kuning Aik Bone, Tereng Kuning Aik Bone",Buka 24 jam,None,Lombok
1093,https://www.google.com/maps/place/Objek+Wisata...,Objek Wisata Batu Bolong,"4,8",(13),Tujuan Wisata,F3R4+9Q7,Buka 24 jam,None,Lombok

In [ ]:
#values = ['biro', 'dinas', 'kantor', 'tour', 'paket', 'travel', 'pt', 'travelling', 'perusahaan', 'kebudayaan']
#temp = [x for x in gabungan['Type'] if x.lower() in values]
#print(temp)

[]

In [ ]:
#values = ['biro', 'biro wisata', 'dinas kebudayaan', 'kantor Perusahaan', 'tour', 'paket wisata', 'travelling', 'pt']
#gabungan = gabungan[gabungan['Type'].isin(values) == False]
#gabungan=gabungan[gabungan["Type"] not in values]
gabungan1 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Tujuan Wisata'].index)
#gabungan1
#print(gabungan1)
gabungan2 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Tourist attraction'].index)
gabungan3 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Kafe'].index)
gabungan4 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Taman'].index)
gabungan5 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Area Rekreasi Alam'].index)
gabungan6 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Park'].index)
gabungan7 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Kebun Binatang'].index)
gabungan8 = gabungan.drop(gabungan.loc[gabungan['Type'] != 'Kafetaria'].index)
gabungan7

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
75,https://www.google.com/maps/place/Jakarta+Aqua...,Jakarta Aquarium & Safari,"4,5",(67),Kebun Binatang,Neo Soho @Podomoro City Floor LG 101 - LGM 101...,None,"""Tempat yang menarik dan menyenangkan untuk",Jakarta
755,https://www.google.com/maps/place/Bali+Safari+...,Bali Safari & Marine Park,"4,4",(15.161),Kebun Binatang,Jl. Prof. Dr. Ida Bagus Mantra No.km 19,Pilihan untuk melihat satwa & main air,"""",Bali

In [ ]:
gabungan1.to_csv("gabungan_final1.csv", index=True)
gabungan2.to_csv("gabungan_final2.csv", index=True)
gabungan3.to_csv("gabungan_final3.csv", index=True)
gabungan4.to_csv("gabungan_final4.csv", index=True)
gabungan5.to_csv("gabungan_final5.csv", index=True)
gabungan6.to_csv("gabungan_final6.csv", index=True)
gabungan7.to_csv("gabungan_final7.csv", index=True)
gabungan7.to_csv("gabungan_final8.csv", index=True)                  
extension = 'csv'
all_filenames = [i for i in glob.glob('gabungan_final*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
combined_csv.to_csv("gabungan_all.csv", index=False)
gabungan_all = 'gabungan_all.csv'
gabungan_all = pd.read_csv(gabungan_all)
#gabungan.to_csv("gabungan_semua.csv", index=True)
#gabungan
gabungan_all

,Unnamed: 0,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,59,https://www.google.com/maps/place/'@Jktgoodgui...,@Jktgoodguide,None,None,Tujuan Wisata,"Jl. Kb. Pala I No.295, RT.5/RW.16",Museum terkenal dengan pameran memorial,None,Jakarta
1,61,https://www.google.com/maps/place/Wisata+Serib...,Wisata Seribu PolisiTidur,"4,2",(6),Tujuan Wisata,"Mahoni No.93, RT.4/RW.4",Pameran budaya bahari di Indonesia,"""Anjay udah jadi wisata aja""",Jakarta
2,62,https://www.google.com/maps/place/Tempat+Santa...,Tempat Santai Pinggir Kali Gusuran,None,None,Tujuan Wisata,"PQX9+M2P, Jl. Inspeksi",Masjid bernuansa damai berdesain Belanda,None,Jakarta
3,63,https://www.google.com/maps/place/Kaai%E2%80%9...,Kaai’s house,None,None,Tujuan Wisata,"Gg. H. Ali No.18, RW.5",None,None,Jakarta
4,64,https://www.google.com/maps/place/FEBRI+%26+IF...,FEBRI & IFAN,None,None,Tujuan Wisata,"RVC4+4VC, Jl. Rw. Sel. 2, RT.9/RW.7",Monumen peringatan peristiwa bersejarah,None,Jakarta
...,...,...,...,...,...,...,...,...,...,...
442,33,https://www.google.com/maps/place/Taman+Burung...,Taman Burung TMII,4.6,"(2,007)",Park,MWX3+PFW,Large domed bird park with 300+ species,"""",Jakarta
443,75,https://www.google.com/maps/place/Jakarta+Aqua...,Jakarta Aquarium & Safari,"4,5",(67),Kebun Binatang,Neo Soho @Podomoro City Floor LG 101 - LGM 101...,None,"""Tempat yang menarik dan menyenangkan untuk",Jakarta
444,755,https://www.google.com/maps/place/Bali+Safari+...,Bali Safari & Marine Park,"4,4",(15.161),Kebun Binatang,Jl. Prof. Dr. Ida Bagus Mantra No.km 19,Pilihan untuk melihat satwa & main air,"""",Bali
445,75,https://www.google.com/maps/place/Jakarta+Aqua...,Jakarta Aquarium & Safari,"4,5",(67),Kebun Binatang,Neo Soho @Podomoro City Floor LG 101 - LGM 101...,None,"""Tempat yang menarik dan menyenangkan untuk",Jakarta
446,755,https://www.google.com/maps/place/Bali+Safari+...,Bali Safari & Marine Park,"4,4",(15.161),Kebun Binatang,Jl. Prof. Dr. Ida Bagus Mantra No.km 19,Pilihan untuk melihat satwa & main air,"""",Bali

In [ ]:
#gabungan = 'gabungan_semua.csv'
#gabungan = pd.read_csv(gabungan)
gabungan_all.drop_duplicates(subset='Source', keep = False, inplace=True)
gabungan_all = gabungan_all.drop(columns=['Unnamed: 0'])
gabungan_all.to_csv('gabungan_all.csv', index=True)
gabungan_all

,Source,Place,Rating,Jumlah review,Type,Address,description,Komentar,Kota
0,https://www.google.com/maps/place/'@Jktgoodgui...,@Jktgoodguide,None,None,Tujuan Wisata,"Jl. Kb. Pala I No.295, RT.5/RW.16",Museum terkenal dengan pameran memorial,None,Jakarta
1,https://www.google.com/maps/place/Wisata+Serib...,Wisata Seribu PolisiTidur,"4,2",(6),Tujuan Wisata,"Mahoni No.93, RT.4/RW.4",Pameran budaya bahari di Indonesia,"""Anjay udah jadi wisata aja""",Jakarta
2,https://www.google.com/maps/place/Tempat+Santa...,Tempat Santai Pinggir Kali Gusuran,None,None,Tujuan Wisata,"PQX9+M2P, Jl. Inspeksi",Masjid bernuansa damai berdesain Belanda,None,Jakarta
3,https://www.google.com/maps/place/Kaai%E2%80%9...,Kaai’s house,None,None,Tujuan Wisata,"Gg. H. Ali No.18, RW.5",None,None,Jakarta
4,https://www.google.com/maps/place/FEBRI+%26+IF...,FEBRI & IFAN,None,None,Tujuan Wisata,"RVC4+4VC, Jl. Rw. Sel. 2, RT.9/RW.7",Monumen peringatan peristiwa bersejarah,None,Jakarta
...,...,...,...,...,...,...,...,...,...
438,https://www.google.com/maps/place/Masok/data=!...,Masok,None,None,Taman,Jl. Setia Budi No.12,None,None,Semarang
439,https://www.google.com/maps/place/Taman+Pantai...,Taman Pantai Indah,"4,5",(18),Area Rekreasi Alam,"VRGR+C4V, Unnamed Road, RW.10",None,None,Jakarta
440,https://www.google.com/maps/place/Explore+Wisa...,Explore Wisata Alam,None,None,Area Rekreasi Alam,"Jln kemuning 1 Rt.007 /06 No.32D, RT.7/RW.6",None,None,Jakarta
441,https://www.google.com/maps/place/Desa+Wisata+...,Desa Wisata Lerep,"4,6",(488),Area Rekreasi Alam,RT.02/RW.2,None,"""Sukses terus DESA WISATA LEREP 😊""",Semarang
442,https://www.google.com/maps/place/Taman+Burung...,Taman Burung TMII,4.6,"(2,007)",Park,MWX3+PFW,Large domed bird park with 300+ species,"""",Jakarta

In [ ]:
os.getcwd()

'/content/drive/MyDrive/scrapping data/gabungan/gabungan_final'